global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s
scrape_configs:
- job_name: job-service-employee
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
      - http://employee-payroll
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-payroll:9115